"use client";

import { motion } from "framer-motion";
import { Search, CheckCircle2, XCircle, HelpCircle, ExternalLink, Calendar, Filter, Database } from "lucide-react";
import { useState, useMemo } from "react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { Loader2 } from "lucide-react";

const CHECKS = [
  {
    claim: "Scientists have discovered a new element that powers zero-point energy reactors.",
    verdict: "FALSE",
    source: "Global News Network",
    date: "March 15, 2026",
    summary: "The claim stems from a misinterpreted research paper about theoretical quantum states. No such element or reactor exists.",
    tags: ["Tech", "Energy", "Fake News"],
    category: "Science",
  },
  {
    claim: "Central Bank to issue digital currency-only mandate by 2027.",
    verdict: "PARTIALLY TRUE",
    source: "Financial Times (Simulated)",
    date: "March 12, 2026",
    summary: "While the bank is pilot-testing a CBDC, there is no official mandate to remove physical currency entirely by 2027.",
    tags: ["Economy", "Finance"],
    category: "Economy",
  },
  {
    claim: "New global treaty signed to regulate AI development in space.",
    verdict: "TRUE",
    source: "UN Press (Simulated)",
    date: "March 10, 2026",
    summary: "The Space AI Regulation Act (SARA) was ratified by 142 nations to ensure ethical AI deployment in satellite networks.",
    tags: ["AI", "International", "Space"],
    category: "Technology",
  },
];

export default function FactCheckPage() {
  const [search, setSearch] = useState("");
  const [isSearching, setIsSearching] = useState(false);

  const handleResearch = async () => {
    if (!search.trim()) {
      toast.error("Please enter a research query.");
      return;
    }

    setIsSearching(true);
    toast.loading("Initializing deep-web research scan...", { id: "research" });
    
    // Simulate complex analysis
    await new Promise((r) => setTimeout(r, 2000));
    
    setIsSearching(false);
    toast.success(`Research complete. Archive filtered for: ${search}`, { id: "research" });
  };

  const handleDownload = (check: typeof CHECKS[0]) => {
    const reportContent = `
TRUTHGUARD VERIFICATION REPORT
------------------------------
CLAIM: ${check.claim}
VERDICT: ${check.verdict}
CATEGORY: ${check.category}
SOURCE: ${check.source}
DATE: ${check.date}

SUMMARY:
${check.summary}

TAGS: ${check.tags.join(", ")}

This report was generated by TruthGuard Cyber Intelligence Matrix.
AUTHENTICITY SECURED.
    `.trim();

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `truthguard-report-${check.category.toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Intelligence report downloaded successfully.");
  };

  const filteredChecks = useMemo(() => {
    return CHECKS.filter(check => 
      check.claim.toLowerCase().includes(search.toLowerCase()) ||
      check.category.toLowerCase().includes(search.toLowerCase())
    );
  }, [search]);

  return (
    <main className="relative min-h-screen py-24 px-4 overflow-hidden">
      {/* Background Gradients */}
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(99,102,241,0.08),_transparent_25%),radial-gradient(circle_at_80%_20%,_rgba(34,211,238,0.05),_transparent_30%)]" />

      <div className="container mx-auto max-w-[1200px] relative z-10">
        <header className="mb-12 text-center space-y-4">
          <div className="inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-4 py-1.5 text-[10px] font-bold uppercase tracking-widest text-cyan-400">
            <Database className="h-3.5 w-3.5" />
            Verification Archive
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight">
            Fact-Check <span className="text-cyan-400">Library</span>
          </h1>
          <p className="text-slate-400 max-w-2xl mx-auto text-lg">
            A comprehensive, AI-indexed database of verified claims and debunked misinformation from across the digital landscape.
          </p>
        </header>

        {/* Search Section */}
        <div className="max-w-3xl mx-auto mb-16">
          <div className="relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-indigo-500 to-cyan-500 rounded-[32px] blur opacity-20 group-hover:opacity-40 transition duration-1000"></div>
            <div className="relative flex items-center bg-slate-950 border border-white/10 rounded-[28px] p-2">
              <Search className="ml-4 h-6 w-6 text-slate-500" />
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search claims, topics, or organizations..."
                className="w-full h-14 bg-transparent border-none text-white px-4 outline-none placeholder:text-slate-600"
              />
              <button 
                onClick={handleResearch}
                disabled={isSearching}
                className="h-12 px-8 rounded-2xl bg-white text-slate-950 font-bold text-sm uppercase tracking-widest hover:bg-cyan-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {isSearching ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                {isSearching ? "Analyzing" : "Research"}
              </button>
            </div>
          </div>
          
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            <span className="text-xs font-bold text-slate-600 uppercase tracking-widest mr-2">Trending:</span>
            {["AI Deepfakes", "Election Data", "Climate Change", "Tech Monopolies"].map((tag) => (
              <button key={tag} className="px-4 py-1.5 rounded-full border border-white/5 bg-white/5 text-[10px] font-bold text-slate-400 hover:border-cyan-400/30 hover:text-cyan-400 transition-all">
                {tag}
              </button>
            ))}
          </div>
        </div>

        {/* Results List */}
        <div className="grid gap-6">
          {filteredChecks.length > 0 ? (
            filteredChecks.map((check, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.1 }}
                className="group rounded-[32px] border border-white/10 bg-white/5 p-8 transition-all hover:bg-white/[0.08] hover:border-white/20"
              >
                <div className="flex flex-col lg:flex-row gap-8">
                  <div className="flex-grow space-y-6">
                    <div className="flex flex-wrap items-center gap-4">
                      <div className={cn(
                        "inline-flex items-center gap-2 rounded-full px-4 py-1.5 text-xs font-black uppercase tracking-widest",
                        check.verdict === "TRUE" ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" :
                        check.verdict === "FALSE" ? "bg-red-500/10 text-red-400 border border-red-500/20" :
                        "bg-amber-500/10 text-amber-400 border border-amber-500/20"
                      )}>
                        {check.verdict === "TRUE" ? <CheckCircle2 className="h-3.5 w-3.5" /> : 
                         check.verdict === "FALSE" ? <XCircle className="h-3.5 w-3.5" /> : 
                         <HelpCircle className="h-3.5 w-3.5" />}
                        {check.verdict}
                      </div>
                      <span className="text-[10px] text-slate-500 font-bold uppercase tracking-[0.2em]">{check.category}</span>
                    </div>

                    <h2 className="text-2xl font-bold text-white leading-tight">{check.claim}</h2>
                    
                    <p className="text-slate-400 leading-relaxed">{check.summary}</p>
                    
                    <div className="flex flex-wrap gap-2">
                      {check.tags.map(tag => (
                        <span key={tag} className="text-[10px] font-bold text-cyan-400/70 border border-cyan-400/20 rounded-lg px-2 py-1 uppercase tracking-tighter cursor-default">
                          #{tag}
                        </span>
                      ))}
                    </div>
                  </div>

                  <div className="lg:w-80 space-y-4 pt-4 lg:pt-0 lg:pl-8 lg:border-l border-white/10">
                    <div className="space-y-1">
                      <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Source Entity</div>
                      <div className="text-sm font-bold text-white flex items-center gap-2">
                        {check.source}
                        <ExternalLink className="h-3.5 w-3.5 text-cyan-400/50" />
                      </div>
                    </div>
                    <div className="space-y-1">
                      <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Verification Date</div>
                      <div className="text-sm font-bold text-white flex items-center gap-2">
                        <Calendar className="h-3.5 w-3.5 text-slate-500" />
                        {check.date}
                      </div>
                    </div>
                    <button 
                      onClick={() => handleDownload(check)}
                      className="w-full py-4 rounded-2xl bg-white/5 border border-white/10 text-xs font-bold text-white uppercase tracking-widest hover:bg-white/10 transition-all mt-4"
                    >
                      View Full Report
                    </button>
                  </div>
                </div>
              </motion.div>
            ))
          ) : (
            <div className="text-center py-20 bg-white/5 border border-white/10 border-dashed rounded-[32px]">
              <Database className="h-12 w-12 text-slate-700 mx-auto mb-4" />
              <h3 className="text-lg font-bold text-slate-400">No matching claims found in the archive.</h3>
              <p className="text-slate-600 text-sm mt-2">Adjust your filters or try a broader search term.</p>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}
